spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: dkw123654
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #上传文件总的最大值
      max-request-size: 10MB
      #上传文件的最大值
      max-file-size: 10MB
#  resources:
#    chain:
#      stratege:
#        content:
#          enabled: true
#          path: /**
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mybatis/mapper/*.xml

